spring.application.name=backend

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/studentMisPortal
spring.datasource.username=postgres
spring.datasource.password=postgres

server.servlet.context-path=/api